version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "python"
        versions:
          - ">=3.13"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
