services:
  webauthn:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: WebAuthnServer
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped