// What the tech lead's Chromium build returned from getClientCapabilities().
export const CHROMIUM_152_CAPABILITIES = {
  conditionalCreate: true,
  conditionalGet: true,
  'extension:appid': true,
  'extension:appidExclude': true,
  'extension:cmtgKey': false,
  'extension:credBlob': true,
  'extension:credProps': true,
  'extension:credentialProtectionPolicy': true,
  'extension:crossDeviceFallbackUrl': false,
  'extension:enforceCredentialProtectionPolicy': true,
  'extension:getCredBlob': true,
  'extension:hmacCreateSecret': true,
  'extension:largeBlob': true,
  'extension:minPinLength': true,
  'extension:payment': true,
  'extension:prf': true,
  hybridTransport: true,
  immediateGet: true,
  passkeyPlatformAuthenticator: true,
  relatedOrigins: true,
  signalAllAcceptedCredentials: true,
  signalCurrentUserDetails: true,
  signalUnknownCredential: true,
  userVerifyingPlatformAuthenticator: true,
};
