"""Utilities for decoding WebAuthn-related payloads for the demo decoder.

The implementation lives in :mod:`server.app.decoder.decode_parts`; this module is
the public face of it and re-exports the pieces callers use. Each fragment
resolves its own names through its own imports, so a name here is the same
object the fragment defines -- patching one of these re-exports changes what
callers of *this module* see, not what the fragments call.
"""
from __future__ import annotations

from .. import attestation
from .decode_parts import (
    binary_extract,
    cbor_lenient,
    cbor_runtime,
    cbor_sequence,
    cbor_strict,
    certificate_extensions,
    certificate_summary,
    conversion_cert_leaf,
    conversion_leaf,
    ctap_classify,
    ctap_convert_leaf,
    ctap_repair_leaf,
    ctap_repair_make,
    ctap_runtime_interpret,
    ctap_runtime_parse,
    details_runtime,
    key_utils,
    pipeline_runtime,
    result_runtime,
    summary_leaf,
    summary_runtime,
)

__all__ = ["decode_payload_text"]

# The decoder entry point.
decode_payload_text = pipeline_runtime.decode_payload_text

# Encoding helpers shared with the attestation package.
colon_hex = attestation.colon_hex
encode_base64url = attestation.encode_base64url
format_hex_bytes_lines = attestation.format_hex_bytes_lines
format_hex_string_lines = attestation.format_hex_string_lines
make_json_safe = attestation.make_json_safe
serialize_attestation_certificate = attestation.serialize_attestation_certificate
summarize_authenticator_extensions = attestation.summarize_authenticator_extensions

# Mapping-key coercion and JSON-safety helpers.
_MISSING = key_utils.MISSING
_coerce_cbor_bytes = key_utils.coerce_cbor_bytes
_generate_key_variants = key_utils.generate_key_variants
_get_mapping_entry = key_utils.get_mapping_entry
_hex_json_safe = key_utils.hex_json_safe
_int_to_key_bytes = key_utils.int_to_key_bytes
_key_variant_identity = key_utils.key_variant_identity
_make_hex_only = key_utils.make_hex_only
_stringify_mapping_keys = key_utils.stringify_mapping_keys

# Binary, hex and COSE key extraction.
_convert_cose_key_for_display = binary_extract._convert_cose_key_for_display
_decode_base64_field = binary_extract._decode_base64_field
_extract_authenticator_bytes = binary_extract._extract_authenticator_bytes
_extract_authenticator_bytes_from_attestation = (
    binary_extract._extract_authenticator_bytes_from_attestation
)
_extract_bytes_from_binary = binary_extract._extract_bytes_from_binary
_extract_hex_from_binary = binary_extract._extract_hex_from_binary
_resolve_cose_algorithm = binary_extract._resolve_cose_algorithm

# Strict CBOR parsing primitives.
_CborDecodingError = cbor_strict._CborDecodingError
_decode_cbor_structure = cbor_strict._decode_cbor_structure
_ensure_cbor_available = cbor_strict._ensure_cbor_available
_float_summary = cbor_strict._float_summary
_parse_cbor_item = cbor_strict._parse_cbor_item
_read_cbor_length = cbor_strict._read_cbor_length

# Lenient CBOR decoding primitives.
_lenient_decode_from = cbor_lenient._lenient_decode_from
_lenient_read_uint = cbor_lenient._lenient_read_uint
_structure_to_value = cbor_lenient._structure_to_value

# CBOR sequence decoding.
_decode_cbor_sequence_impl = cbor_sequence._decode_cbor_sequence_impl

# Certificate extension serialisation.
_DEVICE_IDENTIFIER_NAMES = certificate_extensions._DEVICE_IDENTIFIER_NAMES
_build_certificate_extensions_lines = certificate_extensions._build_certificate_extensions_lines
_format_certificate_extension_header = certificate_extensions._format_certificate_extension_header
_format_certificate_extension_value = certificate_extensions._format_certificate_extension_value
_format_device_identifier_line = certificate_extensions._format_device_identifier_line

# Certificate summary line builders.
_build_fingerprint_lines = certificate_summary._build_fingerprint_lines
_build_signature_lines = certificate_summary._build_signature_lines
_build_subject_key_identifier_lines = certificate_summary._build_subject_key_identifier_lines
_build_subject_public_key_info_lines = certificate_summary._build_subject_public_key_info_lines
_format_certificate_time = certificate_summary._format_certificate_time
_format_public_key_point_lines = certificate_summary._format_public_key_point_lines

# Credential payload conversion leaves.
_build_authenticator_data_payload = conversion_leaf._build_authenticator_data_payload
_build_credential_overview = conversion_leaf._build_credential_overview
_build_credential_payload = conversion_leaf._build_credential_payload
_build_flag_payload = conversion_leaf._build_flag_payload
_collect_response_extras = conversion_leaf._collect_response_extras
_convert_client_data_entry = conversion_leaf._convert_client_data_entry

# Certificate conversion leaves.
_convert_attestation_entry_impl = conversion_cert_leaf._convert_attestation_entry_impl
_convert_attestation_statement_impl = conversion_cert_leaf._convert_attestation_statement_impl
_convert_certificate_bytes_impl = conversion_cert_leaf._convert_certificate_bytes_impl
_convert_certificate_chain_impl = conversion_cert_leaf._convert_certificate_chain_impl
_convert_certificate_payload_impl = conversion_cert_leaf._convert_certificate_payload_impl

# Summary field formatting leaves.
_append_multiline_field = summary_leaf._append_multiline_field
_append_simple_field = summary_leaf._append_simple_field
_build_authenticator_data_lines = summary_leaf._build_authenticator_data_lines
_collect_attested_info = summary_leaf._collect_attested_info
_format_boolean = summary_leaf._format_boolean
_format_counter_value = summary_leaf._format_counter_value
_format_flag_line = summary_leaf._format_flag_line
_format_json_block = summary_leaf._format_json_block
_parse_attested_data = summary_leaf._parse_attested_data

# CTAP map classification and labels.
_GET_ASSERTION_REQUEST_LABELS = ctap_classify._GET_ASSERTION_REQUEST_LABELS
_GET_ASSERTION_RESPONSE_LABELS = ctap_classify._GET_ASSERTION_RESPONSE_LABELS
_MAKE_CREDENTIAL_REQUEST_LABELS = ctap_classify._MAKE_CREDENTIAL_REQUEST_LABELS
_MAKE_CREDENTIAL_RESPONSE_LABELS = ctap_classify._MAKE_CREDENTIAL_RESPONSE_LABELS
_build_labeled_ctap_map = ctap_classify._build_labeled_ctap_map
_classify_ctap_map = ctap_classify._classify_ctap_map
_format_ctap_entry_key = ctap_classify._format_ctap_entry_key
_looks_like_get_assertion_output = ctap_classify._looks_like_get_assertion_output
_looks_like_get_assertion_request = ctap_classify._looks_like_get_assertion_request
_looks_like_make_credential_output = ctap_classify._looks_like_make_credential_output
_looks_like_make_credential_request = ctap_classify._looks_like_make_credential_request
_resolve_ctap_label = ctap_classify._resolve_ctap_label

# CTAP field conversion leaves.
_attempt_decode_cbor_map = ctap_convert_leaf._attempt_decode_cbor_map
_convert_ctap_credential_descriptor = ctap_convert_leaf._convert_ctap_credential_descriptor
_convert_optional_ctap_field = ctap_convert_leaf._convert_optional_ctap_field
_normalize_user_mapping = ctap_convert_leaf._normalize_user_mapping

# CTAP trailing-field repair helpers.
_extract_get_assertion_trailing_from_raw = (
    ctap_repair_leaf._extract_get_assertion_trailing_from_raw
)
_locate_get_assertion_trailing_offset = ctap_repair_leaf._locate_get_assertion_trailing_offset
_split_get_assertion_trailing_fields = ctap_repair_leaf._split_get_assertion_trailing_fields

# CTAP make-credential repair helpers.
_derive_alg_from_auth_data = ctap_repair_make._derive_alg_from_auth_data
_extract_mapping_bytes = ctap_repair_make._extract_mapping_bytes
_extract_mapping_string = ctap_repair_make._extract_mapping_string
_merge_ctap_make_credential = ctap_repair_make._merge_ctap_make_credential
_merge_trailing_signature = ctap_repair_make._merge_trailing_signature
_repair_make_credential_entries = ctap_repair_make._repair_make_credential_entries

# Top-level decode pipeline helpers.
_PEM_CERT_PATTERN = pipeline_runtime._PEM_CERT_PATTERN
_decode_binary_field = pipeline_runtime._decode_binary_field
_decode_binary_input = pipeline_runtime._decode_binary_input
_decode_binary_payload = pipeline_runtime._decode_binary_payload
_decode_json_object = pipeline_runtime._decode_json_object
_decode_pem_certificates = pipeline_runtime._decode_pem_certificates
_decode_public_key_credential = pipeline_runtime._decode_public_key_credential
_expand_cbor_value = pipeline_runtime._expand_cbor_value
_looks_like_pem = pipeline_runtime._looks_like_pem
_try_decode_attestation_object = pipeline_runtime._try_decode_attestation_object
_try_decode_authenticator_data = pipeline_runtime._try_decode_authenticator_data
_try_decode_certificate_bytes = pipeline_runtime._try_decode_certificate_bytes
_try_parse_json = pipeline_runtime._try_parse_json

# CBOR sequence decoding and CTAP repair.
_CTAP_COMMAND_MAP = cbor_runtime._CTAP_COMMAND_MAP
_CTAP_STATUS_MAP = cbor_runtime._CTAP_STATUS_MAP
_decode_cbor_sequence = cbor_runtime._decode_cbor_sequence
_extract_ctap_prefix = cbor_runtime._extract_ctap_prefix
_is_padding_bytes = cbor_runtime._is_padding_bytes
_json_safe_with_stringified_keys = cbor_runtime._json_safe_with_stringified_keys
_repair_get_assertion_entries = cbor_runtime._repair_get_assertion_entries
_try_decode_cbor = cbor_runtime._try_decode_cbor

# CTAP field parsers and converters.
_convert_att_stmt_field = ctap_runtime_parse._convert_att_stmt_field
_convert_auth_data_field = ctap_runtime_parse._convert_auth_data_field
_convert_ctap_allow_list = ctap_runtime_parse._convert_ctap_allow_list
_convert_ctap_user = ctap_runtime_parse._convert_ctap_user
_convert_ctap_user_field = ctap_runtime_parse._convert_ctap_user_field
_convert_pub_key_cred_params = ctap_runtime_parse._convert_pub_key_cred_params
_convert_signature_field = ctap_runtime_parse._convert_signature_field
_convert_user_text_value = ctap_runtime_parse._convert_user_text_value
_decode_trailing_map = ctap_runtime_parse._decode_trailing_map
_extract_lenient_map_entries = ctap_runtime_parse._extract_lenient_map_entries
_extract_signature_from_raw_bytes = ctap_runtime_parse._extract_signature_from_raw_bytes
_format_att_stmt_for_expanded_json = ctap_runtime_parse._format_att_stmt_for_expanded_json
_format_auth_data_for_expanded_json = ctap_runtime_parse._format_auth_data_for_expanded_json
_parse_authenticator_data_bytes = ctap_runtime_parse._parse_authenticator_data_bytes
_summarize_bytes_for_json = ctap_runtime_parse._summarize_bytes_for_json

# CTAP interpretation and expanded JSON.
_GET_ASSERTION_REQUEST_HANDLERS = ctap_runtime_interpret._GET_ASSERTION_REQUEST_HANDLERS
_GET_ASSERTION_RESPONSE_HANDLERS = ctap_runtime_interpret._GET_ASSERTION_RESPONSE_HANDLERS
_MAKE_CREDENTIAL_REQUEST_HANDLERS = ctap_runtime_interpret._MAKE_CREDENTIAL_REQUEST_HANDLERS
_MAKE_CREDENTIAL_RESPONSE_HANDLERS = ctap_runtime_interpret._MAKE_CREDENTIAL_RESPONSE_HANDLERS
_build_get_assertion_expanded_json = ctap_runtime_interpret._build_get_assertion_expanded_json
_build_get_assertion_request_expanded_json = (
    ctap_runtime_interpret._build_get_assertion_request_expanded_json
)
_build_make_credential_expanded_json = ctap_runtime_interpret._build_make_credential_expanded_json
_build_make_credential_request_expanded_json = (
    ctap_runtime_interpret._build_make_credential_request_expanded_json
)
_interpret_ctap_cbor_value = ctap_runtime_interpret._interpret_ctap_cbor_value
_interpret_get_assertion_map = ctap_runtime_interpret._interpret_get_assertion_map
_interpret_get_assertion_request_map = ctap_runtime_interpret._interpret_get_assertion_request_map
_interpret_make_credential_map = ctap_runtime_interpret._interpret_make_credential_map
_interpret_make_credential_request_map = (
    ctap_runtime_interpret._interpret_make_credential_request_map
)

# Client data and authenticator data details.
_binary_summary = details_runtime._binary_summary
_build_client_data_details = details_runtime._build_client_data_details
_describe_authenticator_data_bytes = details_runtime._describe_authenticator_data_bytes
_describe_client_data_from_bytes = details_runtime._describe_client_data_from_bytes
_extract_attestation_certificate = details_runtime._extract_attestation_certificate
_is_client_data_dict = details_runtime._is_client_data_dict
_is_public_key_credential = details_runtime._is_public_key_credential
_parse_attestation_object = details_runtime._parse_attestation_object
_try_decode_utf8 = details_runtime._try_decode_utf8

# Decoder payload and result conversion.
_build_authenticator_section = result_runtime._build_authenticator_section
_build_decoder_payload = result_runtime._build_decoder_payload
_convert_attestation_entry = result_runtime._convert_attestation_entry
_convert_attestation_object_data = result_runtime._convert_attestation_object_data
_convert_attestation_statement = result_runtime._convert_attestation_statement
_convert_authenticator_data_result = result_runtime._convert_authenticator_data_result
_convert_certificate_bytes = result_runtime._convert_certificate_bytes
_convert_certificate_chain = result_runtime._convert_certificate_chain
_convert_certificate_payload = result_runtime._convert_certificate_payload
_convert_certificate_result = result_runtime._convert_certificate_result
_convert_client_data_result = result_runtime._convert_client_data_result
_convert_public_key_credential_data = result_runtime._convert_public_key_credential_data
_convert_result_to_data = result_runtime._convert_result_to_data
_prepare_decoder_response = result_runtime._prepare_decoder_response

# Summary rendering.
_base_type = summary_runtime._base_type
_build_certificate_summary_lines = summary_runtime._build_certificate_summary_lines
_extend_with_attestation_section = summary_runtime._extend_with_attestation_section
_extend_with_authenticator_details = summary_runtime._extend_with_authenticator_details
_extend_with_authenticator_extensions = summary_runtime._extend_with_authenticator_extensions
_extend_with_client_data_details = summary_runtime._extend_with_client_data_details
_extend_with_client_data_entry = summary_runtime._extend_with_client_data_entry
_extend_with_client_extensions = summary_runtime._extend_with_client_extensions
_format_attestation_object_summary = summary_runtime._format_attestation_object_summary
_format_authenticator_data_summary = summary_runtime._format_authenticator_data_summary
_format_cbor_summary = summary_runtime._format_cbor_summary
_format_certificate_summary = summary_runtime._format_certificate_summary
_format_client_data_summary = summary_runtime._format_client_data_summary
_format_generic_summary = summary_runtime._format_generic_summary
_format_json_summary = summary_runtime._format_json_summary
_format_public_key_credential_summary = summary_runtime._format_public_key_credential_summary
_format_result_summary = summary_runtime._format_result_summary
