name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Build Docker image
        run: docker build -t pqc-webauthn .

      - name: Run syntax check
        run: python -m compileall .

      - name: Run import check
        run: |
          python - <<'PY'
          import importlib

          modules = [
              "server.server.app",
              "server.server.metadata",
              "server.server.routes.advanced",
              "server.server.routes.general",
              "server.server.routes.simple",
          ]

          for module in modules:
              importlib.import_module(module)
              print(f"Imported {module}")
          PY

      - name: Run pytest
        run: |
          pytest -v --maxfail=1 --disable-warnings -q