name: Dependabot Auto Merge

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests != null &&
      github.event.workflow_run.pull_requests[0] != null
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot pull request
        uses: actions/github-script@v7
        with:
          script: |
            const pullRequestInfo = context.payload.workflow_run.pull_requests?.[0];
            if (!pullRequestInfo) {
              core.info('No pull request associated with this workflow run.');
              return;
            }
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequestInfo.number,
            });
            if (pullRequest.user.login !== 'dependabot[bot]') {
              core.info('Pull request was not opened by Dependabot.');
              return;
            }
            if (pullRequest.state !== 'open') {
              core.info('Pull request is not open.');
              return;
            }
            if (pullRequest.draft) {
              core.info('Pull request is a draft.');
              return;
            }
            try {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
                merge_method: 'squash',
              });
              core.info(`Merged Dependabot pull request #${pullRequest.number}.`);
            } catch (error) {
              core.info(`Unable to merge pull request: ${error.message}`);
            }
