name: Update FIDO MDS metadata

on:
  schedule:
    - cron: '0 0 */10 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Download latest metadata BLOB
        run: |
          set -euo pipefail
          curl --fail --location --show-error \
            https://mds3.fidoalliance.org/ \
            --output examples/server/server/static/fido-mds3.jws

      - name: Commit and push changes
        run: |
          set -euo pipefail
          if git diff --quiet HEAD -- examples/server/server/static/fido-mds3.jws; then
            echo "Metadata BLOB is already up to date."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add examples/server/server/static/fido-mds3.jws
          git commit -m "chore: update FIDO MDS metadata"
          git push origin HEAD:main
